[[redirects]]
  from = "/api/*"
  to = "https://kalfou-nouvelles-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/image/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
